version: "3.8"

services:
  app:
    build: .
    container_name: proyek-laravelUAS_app
    restart: always
    ports:
      - "9009:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel_net
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: proyek-laravelUAS_db
    restart: always
    environment:
      MYSQL_DATABASE: laravel-inventory-stock
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: proyek-laravelUAS_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "9002:80"
    depends_on:
      - db
    networks:
      - laravel_net

networks:
  laravel_net:

volumes:
  db_data:
